plugins { id 'com.android.application' }

android {
    namespace 'com.rasika.rasi'
    compileSdk 35
    defaultConfig {
        applicationId 'com.rasika.rasi'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }
    signingConfigs {
        release {
            if (System.getenv("CI") && System.getenv("CM_KEYSTORE_PATH")) {
                storeFile file(System.getenv("CM_KEYSTORE_PATH"))
                storePassword System.getenv("CM_KEYSTORE_PASSWORD")
                keyAlias System.getenv("CM_KEY_ALIAS")
                keyPassword System.getenv("CM_KEY_PASSWORD")
            }
        }
    }
    buildTypes {
        release {
            if (System.getenv("CM_KEYSTORE_PATH")) { signingConfig signingConfigs.release }
            minifyEnabled false
        }
    }
}
